name: "Cloudflare OIDC Proxy Action"
description: "Authenticate with Cloudflare OIDC Proxy"

inputs:
  proxy-url:
    description: "Cloudflare OIDC Proxy URL"
    required: true
  proxy-url-path:
    description: "Cloudflare OIDC Proxy URL Path"
    required: false
    default: /prod/openid-connect
  role-to-assume:
    description: "Cloudflare OIDC Proxy Role to Assume"
    required: true
  custom-audience:
    description: "Cloudflare OIDC Proxy Audience"
    required: false
    default: "https://api.cloudflare.com/client/v4"

outputs:
  api_token:
    description: "Cloudflare API Token"
  api_token_expiration:
    description: "Cloudflare API Token Expiration"
  api_token_id:
    description: "Cloudflare API Token ID"

runs:
  using: "node16"
  main: "dist/main/index.js"
